### ISSUE TITLE
Is this open source alternative to InfluxDB cluster feature?

### ISSUE THREAD

**Issue by hyorigo** [chengshiwen/influxdb-cluster#1]
Looks interesting

**Comment by chengshiwen** [comment]
Yes, as you said, this project is an open source alternative to [InfluxDB Enterprise](https://docs.influxdata.com/enterprise_influxdb/v1.8/) and aims to replace InfluxDB Enterprise. 

Currently [InfluxDB Cluster v1.8.10-c1.0.0](https://github.com/chengshiwen/influxdb-cluster/releases/tag/v1.8.10-c1.0.0) is already production ready and provides a good starting point (eg. High-quality code, documentation), and the lack of features such as [Anti-Entropy](https://docs.influxdata.com/enterprise_influxdb/v1.8/administration/anti-entropy/), [influxd-ctl](https://docs.influxdata.com/enterprise_influxdb/v1.8/administration/cluster-commands/#influxd-ctl-cluster-management-utility) subcommands, will also be launched in v1.8.10-c1.1.0, v1.8.10-c1.2.0
