### ISSUE TITLE
是否支持账号和密码登录

### ISSUE THREAD

**Issue by yuebinqian** [chengshiwen/influxdb-cluster#10]
该机器是否支持账号和密码登录

**Comment by chengshiwen** [comment]
像官方influxdb一样，需要对每个influxdb设置账号和密码

**Comment by yuebinqian** [comment]
该集群能否支持集群备份和导入、水平扩展集群

**Comment by chengshiwen** [comment]
> 集群备份和导入

计划10月底v1.8.10-c1.2.0发布支持

> 水平扩展集群

这个目前版本v1.8.10-c1.0.0已经支持

备注：本星期会发布v1.8.10-c1.1.0，功能和稳定性持续增加

**Comment by yuebinqian** [comment]
好的，那如果生产上已经使用了v1.8.10-c1.0.0，到时要迁移v1.8.10-c1.2.0这个版本的话，新版本能否支持到把旧版本迁移过去

**Comment by chengshiwen** [comment]
平滑迁移
