### ISSUE TITLE
influxd-ctl show在两个meta节点上查询差异

### ISSUE THREAD

**Issue by MiracleLemon** [chengshiwen/influxdb-cluster#12]
__版本信息:__ [1.8.10-c1.1.0/influxdb-cluster_1.8.10-c1.1.0_static_linux_amd64.tar.gz]

__问题现象:__

1. 三个meta节点存在于两个服务器上
2. 在其中一个服务器上influxd-ctl show正常，另一个服务器上查询异常
3. 如下图所示：
服务器1：
![image](https://user-images.githubusercontent.com/96915580/190981755-42a280e2-a344-4bf6-94b1-32ecb1478f96.png)
服务器2：
![image](https://user-images.githubusercontent.com/96915580/190981831-73ee88bb-7a44-433d-8052-4c08cf135c50.png)

Please run those if possible and link them from a [gist](http://gist.github.com) or simply attach them as a comment to the issue.

*Please note, the quickest way to fix a bug is to open a Pull Request.*

**Comment by chengshiwen** [comment]
节点状态和版本信息，是通过 gossip 进行传播，每秒钟一个节点传播一个节点，10s以内基本就传播完成，达到最终一致，所以刚启动时，如果遇到在不同meta节点上show，Version有的没显示，看看过一段时间是否都能显示？

**Comment by MiracleLemon** [comment]
意思是广播节点信息是在不断重复进行的嘛？
因为在服务器2的meta节点show，Version信息是不断变化的过程：
![image](https://user-images.githubusercontent.com/96915580/191016599-141ac98b-eb7a-4913-90be-c5dd1adcbc0e.png)
![image](https://user-images.githubusercontent.com/96915580/191016731-34519bb4-021c-4058-be15-5a57483d1eed.png)
![image](https://user-images.githubusercontent.com/96915580/191016803-764d89f7-6737-40d3-a382-7ad18ce5f510.png)

**Comment by chengshiwen** [comment]
> 意思是广播节点信息是在不断重复进行的嘛？

是的

每个 meta 和 data 节点都会将自己的状态和版本信息，meta 节点每隔 [gossip-frequency = "5s"](https://docs.influxdata.com/enterprise_influxdb/v1.8/administration/config-meta-nodes/#gossip-frequency--5s)、data 节点每隔 [gossip-frequency = "3s"](https://docs.influxdata.com/enterprise_influxdb/v1.8/administration/config-data-nodes/#gossip-frequency--3s) 传播出去，新的节点收到这个信息后还会携带这个信息加上自己的信息，继续随机传播下去，所以基本上很快就会收敛，每个 meta 节点上 show，都能看到所有节点的状态和版本。这些信息会被保留[announcement-expiration = "30s"](https://docs.influxdata.com/enterprise_influxdb/v1.8/administration/config-meta-nodes/#announcement-expiration--30s)，如果没有新的传播信息过来的话

可以适当调整这 3 个参数

**Comment by chengshiwen** [comment]
关于 Gossip 协议，可以看下面这篇介绍：[Gossip 协议](http://icyfenix.cn/distribution/consensus/gossip.html)

Gossip 传播示意图：
![gossip](http://icyfenix.cn/assets/img/gossip.0eb19e80.gif)

**Comment by MiracleLemon** [comment]
> 另外，在服务器2的 meta 节点 show，会看到 version 都显示的情况吗？
会的，上面的图就是meta节点在服务器2上show的几次结果。

感谢答疑，多谢~~
