### ISSUE TITLE
Failure to add new data node to cluster

### ISSUE THREAD

**Issue by khushu12** [chengshiwen/influxdb-cluster#15]
__System info:__ [Include InfluxDB version, operating system name, and other relevant details]
influx version: 1.8.10-c1.1.2, EC2-ami  ubuntu/images/hvm-ssd/ubuntu-jammy-22.04-amd64-server-20221201

__Steps to reproduce:__

1. [First Step] Followed documentation of creating influxdb cluster using prebuilts. Setup was one meta node and trying to attach 1 data node. Started meta node as single server.
```
sudo /home/ubuntu/influxdb-cluster-1.8.10-c1.1.2-1/usr/bin/influxd-meta -config /home/ubuntu/influxdb-cluster-1.8.10-c1.1.2-1/etc/influxdb/influxdb.conf -single-server &
```
Server was up.
Started data node on different ubuntu box with changes to hostname in the influxdb config file as specified in docs.
```
sudo /home/ubuntu/influxdb-cluster-1.8.10-c1.1.2-1/usr/bin/influxd -config /home/ubuntu/influxdb-cluster-1.8.10-c1.1.2-1/etc/influxdb/influxdb.conf
```

```
ubuntu@ip-172-16-1-144:~/influxdb-cluster-1.8.10-c1.1.2-1/usr/bin$ /home/ubuntu/influxdb-cluster-1.8.10-c1.1.2-1/usr/bin/influxd-ctl show
Data Nodes
==========
ID	TCP Address	Version

Meta Nodes
==========
ID	TCP Address	Version
1	localhost:8091	1.8.10-c1.1.2
```

2. Tried to attach data node with below command by running below command from meta-01
```
/home/ubuntu/influxdb-cluster-1.8.10-c1.1.2-1/usr/bin/influxd-ctl add-data influxdb-data-03:8088
add-data: operation exited with error: read message size: EOF
```
Below Error on datanode influx server
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xf5a79d]

goroutine 45 [running]:
github.com/influxdata/influxdb/coordinator.(*JoinClusterResponse).MarshalBinary(0xc000290678, 0x1, 0x1, 0x0, 0x0, 0xc000290678)
	/root/influxdb/**coordinator/rpc.go:1330 +0x5d**
github.com/influxdata/influxdb/coordinator.EncodeLV(0x2562e00, 0xc000010fc0, 0x255f560, 0xc000290678, 0x0, 0x2562e00)
	/root/influxdb/coordinator/service.go:1594 +0x35
github.com/influxdata/influxdb/coordinator.EncodeTLV(0x2562e00, 0xc000010fc0, 0xc000010f28, 0x255f560, 0xc000290678, 0x1, 0x8)
	/root/influxdb/coordinator/service.go:1586 +0x85
github.com/influxdata/influxdb/coordinator.(*Service).processJoinClusterRequest(0xc000106d80, 0x259fb80, 0xc000010fc0)
	/root/influxdb/coordinator/service.go:1366 +0x2ab
github.com/influxdata/influxdb/coordinator.(*Service).handleConn(0xc000106d80, 0x259fb80, 0xc000010fc0)
	/root/influxdb/coordinator/service.go:422 +0x1466
github.com/influxdata/influxdb/coordinator.(*Service).serve.func1(0xc000106d80, 0x259fb80, 0xc000010fc0)
	/root/influxdb/coordinator/service.go:284 +0x6f
created by github.com/influxdata/influxdb/coordinator.(*Service).serve
	/root/influxdb/coordinator/service.go:282 +0x13f
```

Checking source code looks like node_id is not being passed or is null. Please help to find a fix.

**Comment by chengshiwen** [comment]
@khushu12 
1. `influxd-meta` should use the configuration file `influxdb-meta.conf`, while `influxd` should use `influxdb.conf`
2. Could you provide the modified changes of `influxdb-meta.conf` and `influxdb.conf`?
3. In fact `influxdb-data-03:8088` does not exist, the code will optimize this problem caused by `add-data`
4. Please refer to the installation documentation in detail, step by step: [English|Installation](https://github.com/chengshiwen/influxdb-cluster/wiki/Home-Eng#installation) or [中文|安装](https://github.com/chengshiwen/influxdb-cluster/wiki#%E5%AE%89%E8%A3%85)

**Comment by chengshiwen** [comment]
@khushu12 
Before `influxd-meta` starts, you should specify the `hostname`, otherwise the data node cannot access the `hostname` of the meta node, because the `hostname` of the meta node is `localhost` by default

**Comment by khushu12** [comment]
Thanks got it figured out. Was using incorrect meta config.
