### ISSUE TITLE
sum获取结果为null

### ISSUE THREAD

**Issue by zzm219** [chengshiwen/influxdb-cluster#16]
3data节点 2副本，sum函数2个data节点获取为null，1个data节点获取正常

**Comment by chengshiwen** [comment]
方便提供下：部署的版本信息，以及可复现的步骤吗

**Comment by chengshiwen** [comment]
@zzm219 按照 “3data节点 2副本 sum函数” 目前在 v1.8.10-c1.1.x 上还没有复现，如有复现步骤可以提供下

**Comment by chengshiwen** [comment]
暂时关闭issue，提供复现步骤可以再次打开

**Comment by zzm219** [comment]
@chengshiwen 我用的版本是v1.8.10-c1.1.2，之前有问题的环境将副本改成3暂时规避了这个问题，但是最近新搭的环境复现不了该问题

**Comment by chengshiwen** [comment]
1、执行 `influxd-ctl show-shards -v`，可以查看 rp 为 `raw` 的各个 shard 的互备情况，同时查看 state 为 `cold`（即处于冷数据）的 size 大小，如果 size 明显小于备份节点 shard 的 size，则说明数据少了一部分
2、对有 size 大小不一致的 shard，进行手工拷贝 `influxd-ctl copy-shard` 可以解决

目前初步怀疑可能跟之前数据写入同步有关系，如果再次出现，我进行追踪和修复
