### ISSUE TITLE
Influxdb_data shutting down unexpectedly

### ISSUE THREAD

**Issue by tushar-quartic** [chengshiwen/influxdb-cluster#18]
__System info:__ [Docker image - chengshiwen/influxdb:1.8.10-c1.1.2-data , Using cluster [https://github.com/influxtsdb/helm-charts/tree/master/charts/influxdb-cluster](url)]

__Steps to reproduce:__

1. Execute count query for around 2500 datapoints
2. dial tcp: i/o timeout error occurs
3. On influx logs 
    `ts=2023-02-17T10:14:40.059826Z lvl=info msg="Write failed" log_id=0g3gswpl000 service=write node_id=5 shard_id=35 error="hinted handoff queue not empty"
ts=2023-02-17T10:14:40.061210Z lvl=info msg="failed to store statistics" log_id=0g3gswpl000 service=monitor error="write failed"
ts=2023-02-17T10:14:41.003336Z lvl=info msg=" Signal received, initializing clean shutdown..." log_id=0g3gswpl000
ts=2023-02-17T10:14:41.003369Z lvl=info msg=" Waiting for clean shutdown..." log_id=0g3gswpl000
ts=2023-02-17T10:14:43.857946Z lvl=info msg=" Closing announcer service" log_id=0g3gswpl000 service=announcer
ts=2023-02-17T10:14:43.859061Z lvl=info msg=" Closing retention policy enforcement service" log_id=0g3gswpl000 service=retention
ts=2023-02-17T10:14:43.860097Z lvl=info msg=" Shutting down hinted handoff service" log_id=0g3gswpl000 service=handoff
ts=2023-02-17T10:14:43.971888Z lvl=info msg="Closed service" log_id=0g3gswpl000 service=subscriber
ts=2023-02-17T10:14:43.971943Z lvl=info msg=" Server shutdown completed" log_id=0g3gswpl000`

__Expected behavior: Should not shutdown 

__Actual behavior: Server shutting down

__Additional info:`ts=2023-02-17T10:14:40.059826Z lvl=info msg="Write failed" log_id=0g3gswpl000 service=write node_id=5 shard_id=35 error="hinted handoff queue not empty"
ts=2023-02-17T10:14:40.061210Z lvl=info msg="failed to store statistics" log_id=0g3gswpl000 service=monitor error="write failed"
ts=2023-02-17T10:14:41.003336Z lvl=info msg=" Signal received, initializing clean shutdown..." log_id=0g3gswpl000
ts=2023-02-17T10:14:41.003369Z lvl=info msg=" Waiting for clean shutdown..." log_id=0g3gswpl000
ts=2023-02-17T10:14:43.857946Z lvl=info msg=" Closing announcer service" log_id=0g3gswpl000 service=announcer
ts=2023-02-17T10:14:43.859061Z lvl=info msg=" Closing retention policy enforcement service" log_id=0g3gswpl000 service=retention
ts=2023-02-17T10:14:43.860097Z lvl=info msg=" Shutting down hinted handoff service" log_id=0g3gswpl000 service=handoff
ts=2023-02-17T10:14:43.971888Z lvl=info msg="Closed service" log_id=0g3gswpl000 service=subscriber
ts=2023-02-17T10:14:43.971943Z lvl=info msg=" Server shutdown completed" log_id=0g3gswpl000`

**Comment by chengshiwen** [comment]
@tushar-quartic Could you show `Last State` in influxdb pods by `kubectl describe pod influxdb-cluster-data-x`, which includes `Reason` and `Exit Code`. Maybe the last state's reason is `OOMKilled`, which helps us find the problem.

**Comment by chengshiwen** [comment]
Close this issue since no updates for long time.
