### ISSUE TITLE
All nodes in the cluster are crashed when multiple writing stress testing and 16 million total points written per second

### ISSUE THREAD

**Issue by andyli029** [chengshiwen/influxdb-cluster#21]
__System info:__ [Include InfluxDB version, operating system name, and other relevant details]

__Steps to reproduce:__

1. [First Step]
2. [Second Step]
3. [and so on...]

__Expected behavior:__ [What you expected to happen]

__Actual behavior:__ [What actually happened]

__Additional info:__ [Include gist of relevant config, logs, etc.]
```
# influxd-ctl show
all Nodes
Data Nodes
==========
ID	TCP Address		Version
4	10.90.3.93:8088
5	10.90.3.94:8088
6	10.90.3.95:8088
7	10.90.3.96:8088

Meta Nodes
==========
ID	TCP Address		Version
1	10.90.3.84:8091		unknown
2	10.90.3.85:8091		unknown
3	10.90.3.86:8091		unknown
```
client node return err:
```
[2023-03-14 14:51:20] Error sending write: dial tcp4 10.90.3.94:8086: connect: connection refused
[2023-03-14 14:51:20] Error sending write: dial tcp4 10.90.3.94:8086: connect: connection refused
[2023-03-14 14:51:20] Error sending write: dial tcp4 10.90.3.94:8086: connect: connection refused
[2023-03-14 14:51:20] Error sending write: dial tcp4 10.90.3.94:8086: connect: connection refused
[2023-03-14 14:51:20] Error sending write: dial tcp4 10.90.3.94:8086: connect: connection refused
[2023-03-14 14:51:20] Error sending write: dial tcp4 10.90.3.94:8086: connect: connection refused
[2023-03-14 14:51:20] Error sending write: dial tcp4 10.90.3.94:8086: connect: connection refused
[2023-03-14 14:51:20] Error sending write: dial tcp4 10.90.3.94:8086: connect: connection refused
[2023-03-14 14:51:20] Error sending write: dial tcp4 10.90.3.94:8086: connect: connection refused
[2023-03-14 14:51:20] Error sending write: dial tcp4 10.90.3.94:8086: connect: connection refused
[2023-03-14 14:51:20] Error sending write: dial tcp4 10.90.3.94:8086: connect: connection refused
[2023-03-14 14:51:20] Error sending write: dial tcp4 10.90.3.94:8086: connect: connection refused
```
data node logs:
```
[httpd] 10.90.3.86 - - [14/Mar/2023:14:48:31 +0800] "POST /write?db=stress HTTP/1.1 " 204 0 "-" "fasthttp" 3bf17226-c234-11ed-99ec-fa2020293404 681727
[httpd] 10.90.3.97 - - [14/Mar/2023:14:48:31 +0800] "POST /write?db=stress HTTP/1.1 " 204 0 "-" "fasthttp" 3bf9f1b6-c234-11ed-99f5-fa2020293404 626060
[httpd] 10.90.3.97 - - [14/Mar/2023:14:48:31 +0800] "POST /write?db=stress HTTP/1.1 " 204 0 "-" "fasthttp" 3c01058a-c234-11ed-9a07-fa2020293404 579819
[httpd] 10.90.3.98 - - [14/Mar/2023:14:48:31 +0800] "POST /write?db=stress HTTP/1.1 " 204 0 "-" "fasthttp" 3bdb65c6-c234-11ed-99c4-fa2020293404 868305
```

If this is an issue of for performance, locking, etc the following commands are useful to create debug information for the team.

```
curl -o profiles.tar.gz "http://localhost:8086/debug/pprof/all?cpu=true"

curl -o vars.txt "http://localhost:8086/debug/vars"
iostat -xd 1 30 > iostat.txt
```

**Please note** It will take at least 30 seconds for the first cURL command above to return a response.
This is because it will run a CPU profile as part of its information gathering, which takes 30 seconds to collect.
Ideally you should run these commands when you're experiencing problems, so we can capture the state of the system at that time.

If you're concerned about running a CPU profile (which only has a small, temporary impact on performance), then you can set `?cpu=false` or omit `?cpu=true` altogether.

Please run those if possible and link them from a [gist](http://gist.github.com) or simply attach them as a comment to the issue.

*Please note, the quickest way to fix a bug is to open a Pull Request.*

**Comment by chengshiwen** [comment]
@andyli029 This error seems to be caused by a lot of stress writing sources. Because one stress write source will make the cpu and memory of all data nodes become fully loaded, and multiple stress write sources will only cause all data nodes to go down.

**Comment by chengshiwen** [comment]
Additional information: **240 million total points** written per second

```
cat 2stress.sh
/usr/bin/influx-stress insert -r 200s --strict --pps 4000000 --host http://10.90.3.93:8086 >> /root/out_stress.log &
/usr/bin/influx-stress insert -r 200s --strict --pps 4000000 --host http://10.90.3.94:8086 >> /root/out_stress.log &
/usr/bin/influx-stress insert -r 200s --strict --pps 4000000 --host http://10.90.3.95:8086 >> /root/out_stress.log &
/usr/bin/influx-stress insert -r 200s --strict --pps 4000000 --host http://10.90.3.96:8086 >> /root/out_stress.log &
```

**Comment by andyli029** [comment]
Maybe I find the core reason:
```
Mar 14 21:18:03 kernel: Out of memory: Kill process 17944 (influxd) score 847 or sacrifice child
Mar 14 21:18:03 kernel: Killed process 17944 (influxd), UID 0, total-vm:33462440kB, anon-rss:28731572kB, file-rss:0kB, shmem-rss:0kB
```

**Comment by chengshiwen** [comment]
This kind of crash problem is OOMKilled, which is similar to the #19 issue.

<img width="955" alt="image" src="https://user-images.githubusercontent.com/4902714/225194418-16ca5198-4552-4f29-9fa3-b413401cfd20.png">
