### ISSUE TITLE
Unexpected write: status 500 , body: {"error":"timeout"}, when 16 million total points written per second

### ISSUE THREAD

**Issue by andyli029** [chengshiwen/influxdb-cluster#22]
__System info:__ [Include InfluxDB version, operating system name, and other relevant details]

__Steps to reproduce:__

1. [First Step]
2. [Second Step]
3. [and so on...]

__Expected behavior:__ [What you expected to happen]

__Actual behavior:__ [What actually happened]

__Additional info:__ [Include gist of relevant config, logs, etc.]

If this is an issue of for performance, locking, etc the following commands are useful to create debug information for the team.

```
curl -o profiles.tar.gz "http://localhost:8086/debug/pprof/all?cpu=true"

curl -o vars.txt "http://localhost:8086/debug/vars"
iostat -xd 1 30 > iostat.txt
```

**Please note** It will take at least 30 seconds for the first cURL command above to return a response.
This is because it will run a CPU profile as part of its information gathering, which takes 30 seconds to collect.
Ideally you should run these commands when you're experiencing problems, so we can capture the state of the system at that time.

If you're concerned about running a CPU profile (which only has a small, temporary impact on performance), then you can set `?cpu=false` or omit `?cpu=true` altogether.

Please run those if possible and link them from a [gist](http://gist.github.com) or simply attach them as a comment to the issue.

*Please note, the quickest way to fix a bug is to open a Pull Request.*

**Comment by chengshiwen** [comment]
@andyli029 Many reasons can cause this error, such as the performance capacity of cpu and memory, such as too many tcp connections, such as unreasonable [write-timeout = "10s"](https://docs.influxdata.com/enterprise_influxdb/v1.8/administration/config-data-nodes/#write-timeout--10s), etc.

Usually, insufficient hardware resources are a common cause.

**Comment by chengshiwen** [comment]
Additional information: This error occurred under issue #21, which requires **160 million total points** written per second under 4 servers with 32C32GB

**Comment by chengshiwen** [comment]
Additional information:

```
Unexpected write: status 500 , body: {"error":"write failed: dial tcp 10.90.3.94:8088: i/o timeout"}
```

Maybe [dial-timeout = "1s"](https://docs.influxdata.com/enterprise_influxdb/v1.8/administration/config-data-nodes/#dial-timeout--1s) should be adjusted to a larger value.

**Comment by andyli029** [comment]
> Additional information:
> 
> ```
> Unexpected write: status 500 , body: {"error":"write failed: dial tcp 10.90.3.94:8088: i/o timeout"}
> ```
> 
> Maybe [dial-timeout = "1s"](https://docs.influxdata.com/enterprise_influxdb/v1.8/administration/config-data-nodes/#dial-timeout--1s) should be adjusted to a larger value.

but the another case:
```
Unexpected write: status 500 , body: {"error":"timeout"}
```

**Comment by chengshiwen** [comment]
<img width="1438" alt="image" src="https://user-images.githubusercontent.com/4902714/225023361-255b80cd-1150-432d-b851-62187a354068.png">

<img width="487" alt="image" src="https://user-images.githubusercontent.com/4902714/225023058-ca1eaa27-65e5-4ff8-a460-c646a75f6abc.png">

The number in the red box refers to the processing time from the beginning to the end of the request, and the unit is `μs`. So the number indicates that there are already a large number of http requests that just reach `1000s` under the configuration `write-timeout=1000s`.

You should check the load status of cpu, memory, and tcp numbers, which may cause a backlog of http requests that cannot be processed
