### ISSUE TITLE
Different results with same query when 16 million total points written per second

### ISSUE THREAD

**Issue by andyli029** [chengshiwen/influxdb-cluster#23]
__System info:__ [Include InfluxDB version, operating system name, and other relevant details]

__Steps to reproduce:__
```
> select * from ctr where "some"='tag-6000' and time=1678798961952865493 limit 1;
> select * from ctr where "some"='tag-6000' and time=1678798961952865493 limit 1;
name: ctr
time                n some
----                - ----
1678798961952865493 0 tag-6000

```

1. [First Step]
2. [Second Step]
3. [and so on...]

__Expected behavior:__ [What you expected to happen]

__Actual behavior:__ [What actually happened]

__Additional info:__ [Include gist of relevant config, logs, etc.]

If this is an issue of for performance, locking, etc the following commands are useful to create debug information for the team.

```
curl -o profiles.tar.gz "http://localhost:8086/debug/pprof/all?cpu=true"

curl -o vars.txt "http://localhost:8086/debug/vars"
iostat -xd 1 30 > iostat.txt
```

**Please note** It will take at least 30 seconds for the first cURL command above to return a response.
This is because it will run a CPU profile as part of its information gathering, which takes 30 seconds to collect.
Ideally you should run these commands when you're experiencing problems, so we can capture the state of the system at that time.

If you're concerned about running a CPU profile (which only has a small, temporary impact on performance), then you can set `?cpu=false` or omit `?cpu=true` altogether.

Please run those if possible and link them from a [gist](http://gist.github.com) or simply attach them as a comment to the issue.

*Please note, the quickest way to fix a bug is to open a Pull Request.*

**Comment by chengshiwen** [comment]
@andyli029 In your stress test environment, the write speed has reached 16 million points per second. At the same time, due to insufficient hardware resources, the InfluxDB instance may crash at any time, resulting in data being discarded and data inconsistency. First of all, it is necessary to ensure the stability of machine resources. The **anti entropy** feature to be released next will fix data inconsistencies.

**Comment by andyli029** [comment]
Good job.

**Comment by chengshiwen** [comment]
Please refer to the official document: [Anti-Entropy](https://docs.influxdata.com/enterprise_influxdb/v1.8/administration/anti-entropy/)

**Comment by chengshiwen** [comment]
More details:
- [InfluxDB Wiki](https://github.com/chengshiwen/influxdb-cluster/wiki/Home-Eng)
- [InfluxDB Enterprise](https://docs.influxdata.com/enterprise_influxdb/v1.8/)
