### ISSUE TITLE
I can not pull the Image with portainer - i get "Failure - no such image" - is there a typo?

### ISSUE THREAD

**Issue by WaldemarFech** [chengshiwen/influxdb-cluster#24]
I tried the links from your docker-compose.yml, i changed them to :latest, i tried chengshiwen/influxdb-cluster instead of chengshiwen/influxdb ... but i always get the same error

Portainer is running on a raspberry pi4 - is this maybe the problem - not supporting hardware?

I would like to run 2 Pis redundant - the second one as backup, if the first one breaks.

thanks alot!

**Comment by zqwangadv** [comment]
> run docker pull chengshiwen/influxdb:1.8.10-c1.1.2-meta to pull meta image, run docker pull chengshiwen/influxdb:1.8.10-c1.1.2-data  to pull data image.

**Comment by chengshiwen** [comment]
@WaldemarFech I haven't tried running the container on a raspberry pi4, and can you try the [pre-built binaries](https://github.com/chengshiwen/influxdb-cluster/releases/tag/v1.8.10-c1.1.2) first and see if they work?
