### ISSUE TITLE
dangled meta node

### ISSUE THREAD

**Issue by andyli029** [chengshiwen/influxdb-cluster#25]
__System info:__ [Include InfluxDB version, operating system name, and other relevant details]

__Steps to reproduce:__
1. remove-meta $node
2. add-meta $node
3.  .....
```
add-meta: operation exited with error: dangled meta node at "localhost:8091" already has state present,
 cannot add another meta node
```

1. [First Step]
5. [Second Step]
6. [and so on...]

__Expected behavior:__ [What you expected to happen]

__Actual behavior:__ [What actually happened]

__Additional info:__ [Include gist of relevant config, logs, etc.]

If this is an issue of for performance, locking, etc the following commands are useful to create debug information for the team.

```
curl -o profiles.tar.gz "http://localhost:8086/debug/pprof/all?cpu=true"

curl -o vars.txt "http://localhost:8086/debug/vars"
iostat -xd 1 30 > iostat.txt
```

**Please note** It will take at least 30 seconds for the first cURL command above to return a response.
This is because it will run a CPU profile as part of its information gathering, which takes 30 seconds to collect.
Ideally you should run these commands when you're experiencing problems, so we can capture the state of the system at that time.

If you're concerned about running a CPU profile (which only has a small, temporary impact on performance), then you can set `?cpu=false` or omit `?cpu=true` altogether.

Please run those if possible and link them from a [gist](http://gist.github.com) or simply attach them as a comment to the issue.

*Please note, the quickest way to fix a bug is to open a Pull Request.*

**Comment by chengshiwen** [comment]
If you have multiple meta nodes, DO NOT USE `localhost:8091`, which will cause network communication problem.

**Comment by andyli029** [comment]
@chengshiwen 
Multiple meta nodes exist different nodes.
```
# influxd-ctl show
Sometimes it works, sometimes it doesn't
```

**Comment by chengshiwen** [comment]
@andyli029 What is the result of `influxd-ctl show`?

**Comment by andyli029** [comment]
```
# influxd-ctl show
Data Nodes
==========
ID	TCP Address		Version
4	10.80.51.86:8088	1.8.10-c1.1.2
5	10.80.51.87:8088	1.8.10-c1.1.2

Meta Nodes
==========
ID	TCP Address		Version
2	10.80.51.86:8091	1.8.10-c1.1.2
3	10.80.51.87:8091	1.8.10-c1.1.2

# influxd-ctl show
Data Nodes
==========
ID	TCP Address	Version

Meta Nodes
==========
ID	TCP Address	Version
```

**Comment by chengshiwen** [comment]
The result sometimes disappears, which node are you executing on?

**Comment by andyli029** [comment]
> The result sometimes disappears, which node are you executing on?

Meta Node

**Comment by chengshiwen** [comment]
Is it on node `10.80.51.86:8091` or `10.80.51.87:8091`?

**Comment by andyli029** [comment]
> Is it on node `10.80.51.86:8091` or `10.80.51.87:8091`?

@chengshiwen  yes

**Comment by chengshiwen** [comment]
Are the influxd-ctl show commands executed twice on the same node?

**Comment by chengshiwen** [comment]
If you want to remove a meta node, you should specify the `-bind` option, like

```sh
influxd-ctl -bind meta-node-02:8091 remove-meta meta-node-01:8091
```

**Comment by chengshiwen** [comment]
Also, could you provide steps to reproduce this issue?

**Comment by andyli029** [comment]
> Are the influxd-ctl show commands executed twice on the same node?
Yes

**Comment by chengshiwen** [comment]
This step description is too simple, while detailed and stable reproduction steps include: operating system and version, configuration file information, operation steps, etc., so it can help me reproduce the same issue in my environment.

**Comment by chengshiwen** [comment]
@Ansible-NW Could you provide steps to reproduce this issue?

**Comment by Ansible-NW** [comment]
@chengshiwen On one of my meta node, each time I want to add my third node running this command:
`influxd-ctl add-meta influxdb-meta03:8091`

It show me this error:
`add-meta: operation exited with error: dangled meta node at "localhost:8091" already has state present, cannot add another meta node`

I never add localhost as a nod in my cluster though

**Comment by chengshiwen** [comment]
@Ansible-NW Reset the cluster and all nodes. Then execute the command like
```
influxd-ctl -bind influxdb-meta01:8091 add-meta influxdb-meta01:8091
influxd-ctl -bind influxdb-meta01:8091 add-meta influxdb-meta02:8091
influxd-ctl -bind influxdb-meta01:8091 add-meta influxdb-meta03:8091
```

Please refer to [Manage Clusters](https://github.com/chengshiwen/influxdb-cluster/wiki/Manage-Clusters#--bind-hostnameport-) to learn about the option `-bind`

**Comment by Ansible-NW** [comment]
@chengshiwen thank you. I resetted the cluster and manage to add all the nodes (meta and data) to the cluster. 
I think the problem came from my first integration. I mad sure the node were available on the FQDN but not just from the hostname.

Everything felt to place after I setted up my conf to allow hostname to be pinged.

Just on more question, to install chronograf should I take the deb package from the influxdb official page or do you provide one?

**Comment by chengshiwen** [comment]
@Ansible-NW Just to download he official installation package of chronograf

**Comment by 3174992463** [comment]
`influxd-ctl -bind 192.168.10.3:8091 add-meta 192.168.10.7:8091
Added meta node 1 at localhost:8091

C:\devtools\influxdb-cluster-1.8.11-c1.2.0-1>influxd-ctl -bind 192.168.10.3:8091 show
Data Nodes
==========
ID      TCP Address     Version

Meta Nodes
==========
ID      TCP Address     Version
1       localhost:8091  1.8.11-c1.2.0` 加入meat节点时一直加不进去，总是输出Added meta node 1 at localhost:8091

**Comment by 3174992463** [comment]
- 加入meat节点加不进去
```bash
C:\devtools\influxdb-cluster-1.8.11-c1.2.0-1>influxd-ctl -bind 192.168.10.3:8091 add-meta 192.168.10.3:8091
Added meta node 1 at localhost:8091

C:\devtools\influxdb-cluster-1.8.11-c1.2.0-1>influxd-ctl -bind 192.168.10.3:8091 add-meta 192.168.10.7:8091
Added meta node 1 at localhost:8091

C:\devtools\influxdb-cluster-1.8.11-c1.2.0-1>influxd-ctl -bind 192.168.10.3:8091 add-meta 192.168.10.18:8091
Added meta node 1 at localhost:8091

C:\devtools\influxdb-cluster-1.8.11-c1.2.0-1>influxd-ctl -bind 192.168.10.3:8091 show
Data Nodes
==========
ID      TCP Address     Version

Meta Nodes
==========
ID      TCP Address     Version
1       localhost:8091  1.8.11-c1.2.0

```

**Comment by chengshiwen** [comment]
同 https://github.com/chengshiwen/influxdb-cluster/issues/47
