### ISSUE TITLE
Highly available setup of influxdb cluster

### ISSUE THREAD

**Issue by manoj016** [chengshiwen/influxdb-cluster#31]
System info:
influxdb version: v1.8.10-c1.1.2
OS: Linux influxdb-cluster-data-0 5.4.0-1108-azure #114~18.04.1-Ubuntu SMP Tue Apr 25 19:10:30 UTC 2023 x86_64 GNU/Linux
Docker Image: chengshiwen/influxdb:1.8.10-c1.1.2-data

I want a highly available setup, is it possible to do that using [this](https://github.com/influxtsdb/helm-charts/tree/master/charts/influxdb-cluster)? Right now I am facing issues while querying or writing data when one of the data pod is not running.

__Steps to reproduce:__

1. Run `helm install influxdb-cluster ./influxdb-cluster --set "fullnameOverride=influxdb-cluster"`
2. add data and meta nodes in meta-0 pod
3. stop one of the VM where one of the data pod is running
4. Now all the query and write apis are failing

__Expected behavior:__
All the query and write functionalities should work as expected.

__Actual behavior:__
all the query and write APIs are failing with timeout error

```
[httpd] 10.42.6.73 [31/Aug/2023:09:09:53 +0000] "POST /api/v2/write?org=quartic&bucket=quartic&precision=ns HTTP/1.1" 500 25 "-" "influxdb-client-java/0.1.0-SNAPSHOT" 25985edc-47de-11ee-a5f2-0e3e75d11849 26307
ts=2023-08-31T09:09:53.438196Z lvl=error msg="[500] - \"write failed\"" log_id=0jvfgjøW000 service=httpd
ts=2023-08-31T09:09:53.454397Z lvl-info msg="Write failed" log_id=ØjvfgjøW000 service=write node_id=4 shard_id=46_error="hinted handoff queue not empty"
ts=2023-08-31T09:09:53.454404Z lvl-info msg="Write failed" log_id=0jvfgjøW000 service=write node_id=4 shard_id=47 error="hinted handoff queue not empty"
[httpd] 10.42.6.73 [31/Aug/2023:09:09:53 +0000] "POST /api/v2/write?org=quartic&bucket=quartic&precision=ns HTTP/1.1" 500 25 "-" "influxdb-client-java/0.1.0-SNAPSHOT" 259b96cf-47de-11ee-a5f3-0e3e75d11849 21548
ts=2023-08-31T09:09:53.454520Z lvl-error msg="[500] \"write failed\"" log_id=0jvfgjøW000 service=httpd
ts=2023-08-31T09:09:53.477233Z lvl-info msg="Write failed" log_id=0jvfgjøW000 service=write node_id=4 shard_id=46 error="hinted handoff queue not empty"
ts=2023-08-31T09:09:53.477249Z lvl-info msg="Write failed" log_id=ØjvfgjøW000 service=write node_id=4 shard_id=47_error="hinted handoff queue not empty"
[httpd] 10.42.6.73
[31/Aug/2023:09:09:53 +0000] "POST /api/v2/write?org-quartic&bucket=quartic&precision=ns HTTP/1.1 500 25 "-" "influxdb-client-java/0.1.0-SNAPSHOT" 259dce85-47de-11ee-a5f4-0e3e75d11849 29861
ts=2023-08-31T09:09:53.477389Z lvl-error_msg="[500] \"write failed\"" log_id=0jvfgjøW000 service=httpd
[httpd] 10.42.7.108 quartic_influx_read_write [31/Aug/2023:09:09:47 +0000] "POST /api/v2/query HTTP/1.1 500 51 "Python/3.9 aiohttp/3.8.1" 222784e5-47de-11ee-a5e5-0e3e75d11849 10012524
ts=2023-08-31T09:09:57.651665Z lvl=error msg="[500] - \"dial tcp 10.42.3.113:8088: i/o timeout\'
\"" log_id=0jvfgj0W000 service=httpd
[httpd] 10.42.7.108 - quartic_influx_read_write [31/Aug/2023:09:09:47 +0000] "POST /api/v2/query HTTP/1.1 500 51 "-" "Python/3.9 aiohttp/3.8.1" 222865e6-47de-11ee-a5e6-0e3e75d11849 10011211
ts=2023-08-31T09:09:57.656105Z lvl=error msg="[500] - \"dial tcp 10.42.3.113:8088: i/o timeout\" log_id=0jvfgj0W000 service=httpd
[httpd] 10.42.4.1 [31/Aug/2023:09:09:57 +0000] "GET /ping HTTP/1.1" 204 0 "kube-probe/1.27" 282e4d72-47de-11ee-a5f5-0e3e75d11849 48
[httpd] 10.42.4.1 [31/Aug/2023:09:09:57 +0000] "GET /ping HTTP/1.1" 204 0 -" "kube-probe/1.27" 282e4f1f-47de-11ee-a5f6-0e3e75d11849 35
```

**Comment by chengshiwen** [comment]
Please refer to:
- [InfluxDB Enterprise Clustering](https://docs.influxdata.com/enterprise_influxdb/v1.8/concepts/clustering/)
- [InfluxDB Enterprise data node](https://docs.influxdata.com/enterprise_influxdb/v1.8/concepts/glossary/#data-node)

For high availability, installations must have at least two data nodes. The number of data nodes in your cluster must be the same as your highest replication factor. Any replication factor greater than two gives you additional fault tolerance and query capacity within the cluster.

In k8s, you also need to pay attention to avoid all data nodes running on one node. You can use `affinity` and `podAntiAffinity` to solve this problem.

**Comment by manoj016** [comment]
Thank you so much @chengshiwen, I was able to fix this issue by following this doc https://docs.influxdata.com/enterprise_influxdb/v1.8/guides/rebalance/
