### ISSUE TITLE
InfluxDBIOException: java.net.SocketTimeoutException: timeout

### ISSUE THREAD

**Issue by zhaohuigu-edward** [chengshiwen/influxdb-cluster#34]
![1701153259082](https://github.com/chengshiwen/influxdb-cluster/assets/72776869/912c6de1-4ad5-40ca-9136-ae578c536c38)

**Comment by zhaohuigu-edward** [comment]
利用集群进行数据存储和查询 效果还不如单机 面对大数据量的入库和查询 出现入库异常和查询缓慢情况

**Comment by chengshiwen** [comment]
如果要测试出正常的结果，需要搭建合理的测试环境以及做出适当的配置。采用docker-compose进行测试，网络和磁盘都会受限；同时客户端采用了不合理的多线程编程方式，也会导致出不符合预期的问题。具体地，可以参考 [官方硬件规划指南 Hardware sizing guidelines](https://docs.influxdata.com/enterprise_influxdb/v1/guides/hardware_sizing/)
