### ISSUE TITLE
How can I automate the process of adding the data and meta nodes?

### ISSUE THREAD

**Issue by besrabasant** [chengshiwen/influxdb-cluster#35]
Currently, I add the data and meta node by executing the commands as provided in the documentation
```
docker exec -it influxdb-meta-01 bash
influxd-ctl add-meta influxdb-meta-01:8091
influxd-ctl add-meta influxdb-meta-02:8091
influxd-ctl add-meta influxdb-meta-03:8091
influxd-ctl add-data influxdb-data-01:8088
influxd-ctl add-data influxdb-data-02:8088
```

How can I automate this process on the initialization of  the cluster and also on the addition of new data and meta nodes?

**Comment by chengshiwen** [comment]
influxdb-cluster itself does not support it. You need to use the capabilities of additional tools, such as sidecar in k8s, or writing some scripts that automatically discover and execute commands.

**Comment by besrabasant** [comment]
Do you have an example code or snippet that I can use as a reference?

**Comment by chengshiwen** [comment]
1. [Init Containers](https://kubernetes.io/docs/concepts/workloads/pods/init-containers/)
2. [Understanding Init Containers and Sidecar Containers in Kubernetes])(https://medium.com/@manojkumar_41904/understanding-init-containers-and-sidecar-containers-in-kubernetes-ca94bec10a7b)
3. [Kubernetes Sidecar Containers: Practical Guide with Examples](https://komodor.com/learn/kubernetes-sidecar-containers-practical-guide-with-examples/)
