### ISSUE TITLE
8个datanode 同样sql多次查询结果不一致

### ISSUE THREAD

**Issue by ls0602152** [chengshiwen/influxdb-cluster#36]
大佬好，我这边部署完使用过程中发现同一条sql查询，会出现某些datanode返回空的情况。

部署概况：
版本1.8.10-c1.1.2
meta node 3台
data node 8台
表是 2副本，4分片
查询sql是 select sum("tps") from "domain_metric"  where time >= now() - 30m and time < now() and  "host" = 'abc.com'  and  "http_code" = '500'    group by time(60s) fill(0)

使用负载均衡轮询查询8台节点，连续查询100次，会有10%的概率出现。
循环逐台查询，每台100次，有3台会20次以上为空，有2台不会出现为空，还有3台会出现10次以内为空。
多次测试发现返回空情况跟哪台datanode 没有特殊绑定关系。

这个情况和 [#16](https://github.com/chengshiwen/influxdb-cluster/issues/16) 类似么？

**Comment by chengshiwen** [comment]
因为网络抖动、突然崩溃、掉电宕机等各种因素，各个节点数据刷盘也存在细微的时间差，出故障可能就会出现数据不同步，查询时因为有随访访问可读节点，就会有不一致的情况，hinted handoff 已经能解决大部分，后面 anti-entropy 支持后，也能自动实现同步，不需要手动

因为上面有可能一些原因，导致了过去不一致，目前不一致的解决办法：
1、执行 `influxd-ctl show-shards -v`，可以查看各个 shard 的互备情况，同时查看 state 为 cold（即处于冷数据）的 size 大小，如果size明显小于备份节点 shard 的 size，则说明数据少了一部分
2、对有问题的 db/rp 的 shard，进行手工拷贝 `influxd-ctl copy-shard`

**Comment by ls0602152** [comment]
明白，感谢大佬解答。稍微再请教一下两个问题。
1. 我通过 ```influxd-ctl show-shards -v``` 比对数据确实副本之间有偏差，size做差，差小的几十，差大的两千左右。size大概是94575214 这样一个量级。不过我理解即便不同副本之间数据有差异，是不是也不会返回为空。因为sql正常查询的数据是30分钟区间的聚合数据，一分钟一个点，正常会有30个点。异常情况是一个点都没有返回是因为查询直接中断返回了么？
2. 冷数据可以通过copy做到一致，是不是hot数据就只能等 anti-entropy 支持了（目前我这边的rp是15天，所以按照官方推荐shardGroupDuration是24h）
附data的配置，机器的硬件配置是16C32G 100G
bind-address = ":8088"
hostname = "influx-data-08"
gossip-frequency = "3s"

[meta]
  meta-tls-enabled = false
  meta-insecure-tls = false
  meta-auth-enabled = false
  meta-internal-shared-secret = ""
  dir = "/export/influxdb/meta"
  retention-autocreate = true
  logging-enabled = true

[data]
  dir = "/export/influxdb/data"
  index-version = "inmem"
  wal-dir = "/export/influxdb/wal"
  wal-fsync-delay = "0s"
  validate-keys = false
  strict-error-handling = false
  query-log-enabled = false
  cache-max-memory-size = 2147483648
  cache-snapshot-memory-size = 52428800
  cache-snapshot-write-cold-duration = "10m0s"
  compact-full-write-cold-duration = "4h0m0s"
  compact-throughput = 1073741824
  compact-throughput-burst = 1073741824
  max-series-per-database = 10000000
  max-values-per-tag = 1000000
  max-concurrent-compactions = 0
  max-index-log-file-size = 52428800
  series-id-set-cache-size = 1000
  series-file-max-concurrent-snapshot-compactions = 0
  trace-logging-enabled = false
  tsm-use-madv-willneed = false

[coordinator]
  dial-timeout = "1s"
  pool-max-idle-streams = 100
  pool-max-idle-time = "1m0s"
  allow-out-of-order-writes = false
  shard-reader-timeout = "0s"
  https-enabled = false
  https-certificate = ""
  https-private-key = ""
  https-insecure-tls = false
  cluster-tracing = false
  write-timeout = "20s"
  max-concurrent-queries = 0
  query-timeout = "0s"
  log-queries-after = "0s"
  max-select-point = 0
  max-select-series = 0
  max-select-buckets = 0

[retention]
  enabled = true
  check-interval = "30m0s"

[shard-precreation]
  enabled = true
  check-interval = "10m0s"
  advance-period = "30m0s"

[monitor]
  store-enabled = false
  store-database = "_internal"
  store-interval = "10s"
  remote-collect-interval = "10s"

[subscriber]
  enabled = true
  http-timeout = "30s"
  insecure-skip-verify = false
  ca-certs = ""
  write-concurrency = 40
  write-buffer-size = 1000

[http]
  enabled = true
  bind-address = ":8086"
  auth-enabled = false
  log-enabled = false
  suppress-write-log = false
  write-tracing = true
  flux-enabled = true
  flux-log-enabled = false
  pprof-enabled = true
  pprof-auth-enabled = false
  debug-pprof-enabled = false
  ping-auth-enabled = false
  prom-read-auth-enabled = false
  https-enabled = false
  https-certificate = "/etc/ssl/influxdb.pem"
  https-private-key = ""
  max-row-limit = 0
  max-connection-limit = 0
  shared-secret = ""
  realm = "InfluxDB"
  unix-socket-enabled = false
  unix-socket-permissions = "0777"
  bind-socket = "/var/run/influxdb.sock"
  max-body-size = 25000000
  access-log-path = ""
  max-concurrent-write-limit = 0
  max-enqueued-write-limit = 0
  enqueued-write-timeout = 30000000000

[logging]
  format = "auto"
  level = "info"
  suppress-logo = false

[[graphite]]
  enabled = false
  bind-address = ":2003"
  database = "graphite"
  retention-policy = ""
  protocol = "tcp"
  batch-size = 5000
  batch-pending = 10
  batch-timeout = "1s"
  consistency-level = "one"
  separator = "."
  udp-read-buffer = 0

[[collectd]]
  enabled = false
  bind-address = ":25826"
  database = "collectd"
  retention-policy = ""
  batch-size = 5000
  batch-pending = 10
  batch-timeout = "10s"
  read-buffer = 0
  typesdb = "/usr/share/collectd/types.db"
  security-level = "none"
  auth-file = "/etc/collectd/auth_file"
  parse-multivalue-plugin = "split"

[[opentsdb]]
  enabled = false
  bind-address = ":4242"
  database = "opentsdb"
  retention-policy = ""
  consistency-level = "one"
  tls-enabled = false
  certificate = "/etc/ssl/influxdb.pem"
  batch-size = 1000
  batch-pending = 5
  batch-timeout = "1s"
  log-point-errors = true

[[udp]]
  enabled = false
  bind-address = ":8089"
  database = "udp"
  retention-policy = ""
  batch-size = 5000
  batch-pending = 10
  read-buffer = 0
  batch-timeout = "1s"
  precision = ""

[continuous_queries]
  log-enabled = true
  enabled = true
  query-stats-enabled = false
  run-interval = "1s"

[hinted-handoff]
  enabled = true
  dir = "/export/influxdb/hh"
  max-size = 10737418240
  max-age = "168h0m0s"
  retry-concurrency = 20
  retry-rate-limit = 0
  retry-interval = "1s"
  retry-max-interval = "10s"
  purge-interval = "1m0s"
  batch-size = 512000
  max-writes-pending = 1024

[anti-entropy]
  enabled = false
  check-interval = "5m0s"
  max-fetch = 10
  max-sync = 1
  auto-repair-missing = true

[tls]
  min-version = ""
  max-version = ""

**Comment by chengshiwen** [comment]
1. “不过我理解即便不同副本之间数据有差异，是不是也不会返回为空。因为sql正常查询的数据是30分钟区间的聚合数据，一分钟一个点，正常会有30个点。异常情况是一个点都没有返回是因为查询直接中断返回了么？” —— 这个主要取决于差异数据的情况，有可能某个数据节点确实差了30分钟以上的数据，查询路由到刚刚这个节点上，导致sql为空
2.  anti-entropy 也只会修复 cold 数据，anti-entropy 是自动，而 copy-shard 是手动

**Comment by ls0602152** [comment]
大佬好，更新一下情况。查询不一致问题已经消失。消失原因是之前写入逻辑中会在短时间内（1分钟）更新很多series的fields，假设第一次写入tps是100，覆写后可能变成20或者120。修改逻辑后，保证每个series的每个时间点只写入一次。查询恢复正常。不会出现查询直接返回为 [] 的情况。

**Comment by chengshiwen** [comment]
赞
