### ISSUE TITLE
next version support backup&restore cmd

### ISSUE THREAD

**Issue by JackyeeMe** [chengshiwen/influxdb-cluster#37]
Hi chengshiwen
    em, im curious about that, the next version plan，when could cluster instance support backup&restore command？its really useful to migrate the oss node to cluster node，about the export&import cmd，im afraid it would last huge time, whatever, im trying to test this way, hope this cmd would release soon in the future，thanks for your greatest contribution for opensource.

**Comment by chengshiwen** [comment]
Please refer to [Development Plans](https://github.com/chengshiwen/influxdb-cluster/wiki/Home-Eng#development-plans). The [v1.10.5-c1.2.0](https://github.com/chengshiwen/influxdb-cluster/wiki/Home-Eng#v1105-c120) will be released shortly after [v1.8.10-c1.2.0](https://github.com/chengshiwen/influxdb-cluster/wiki/Home-Eng#v1810-c120) is released, and the estimated date is at the end of this year. Additionally, there is a high probability that [v1.9.13-c1.2.0](https://github.com/chengshiwen/influxdb-cluster/wiki/Home-Eng#v1913-c120) will be skipped directly.
