### ISSUE TITLE
[occurs error] use `influx import` line protocol data file

### ISSUE THREAD

**Issue by JackyeeMe** [chengshiwen/influxdb-cluster#38]
__System info:__ [V1.8.10-c1.1.2]

__Steps to reproduce:__
tip：when export data，i use the `-lponly` command to ignore database and rp，only keep the line data, and the file also present as desired, howerver when i execute the import command，something wrong, i think it may be some issue in bin file (influx)
1. influx_inspect export -lponly ...
2. influx import -database xxx ...

__Expected behavior:__ [import success]

below is the output file screenshot and it coud meet the influx 'Line Protocol format' requirement ~
![image](https://github.com/chengshiwen/influxdb-cluster/assets/156211485/52e6609a-27dc-4ebd-bf0a-60b91a4267a0)

__Actual behavior:__ [error occurs]
![image](https://github.com/chengshiwen/influxdb-cluster/assets/156211485/96584011-f62c-4897-a8eb-f368f51b6433)

**Comment by JackyeeMe** [comment]
emmm, i think maybe found the root cause, the command `influx_inspect -export -lponly` works not correct, open the export file, it has no DML header like below:
# DML
# CONTEXT-DATABASE:xxx
# CONTEXT-RETENTION-POLICY:xxx
# writing tsm data

so i manully add the header, then i could import them, hi , could you please pay attention to this ? @chengshiwen 
![image](https://github.com/chengshiwen/influxdb-cluster/assets/156211485/e52cf2cd-79f3-4fa3-9ef3-b3fa542c679e)

**Comment by JackyeeMe** [comment]
all right, i found the problem, in `export.go` when i send the `-lponly` command, mw descriptor would be closed and prevent the comment header generate, however in `influx.go` import() function use this head, thus the problem occurs
![image](https://github.com/chengshiwen/influxdb-cluster/assets/156211485/254db9d2-f17e-427b-8c84-2fe975ac78f7)

**Comment by chengshiwen** [comment]
Yes, the export option -lponly is necessary for the import command, otherwise only the /write interface can be called, please refer to [Write several points to the database mydb from the file data.txt](https://docs.influxdata.com/influxdb/v1/tools/api/#write-several-points-to-the-database-mydb-from-the-file-datatxt)

**Comment by JackyeeMe** [comment]
> Yes, the option `-lponly` of command `export` is necessary for the `import` command, otherwise only the `/write` HTTP API can be called, please refer to [Write several points to the database mydb from the file data.txt](https://docs.influxdata.com/influxdb/v1/tools/api/#write-several-points-to-the-database-mydb-from-the-file-datatxt)

Yep, thanks for your idea, finally i will use HTTP API to import all the cold data of our OSS instance which belong to the past into cluster instance to try its performance, however, if the handle logic of `-lponly` command in `export.go` which i mentioned as before would have more compatibility in `influx -import` cmd，hope that optimize it between `export -lponly` and `-import` would be better in the next released version, thanks for your contribution again ^.^
