### ISSUE TITLE
timeout: influxd-ctl copy-shard occurs error

### ISSUE THREAD

**Issue by JackyeeMe** [chengshiwen/influxdb-cluster#39]
当我在Meta节点1执行A节点复制分片至B节点时，抛出异常：copy-shard: operation exited with error: read tcp 172.25.38.119:46704->172.25.38.127:8088: i/o timeout，如何解决呀，虚心求助？

**Comment by JackyeeMe** [comment]
@chengshiwen

**Comment by JackyeeMe** [comment]
Hi  @chengshiwen 
    关于这个问题，我说下场景，大概是一个分片组文件夹（假如是50吧），其中包含4个tsm文件，几乎每个文件都达到了2G，然后我不小心删除了一个数据节点下的50文件夹，所以我执行了复制分片操作，每次开始复制到第三个tsm文件的时候，时间大概已耗时30s，meta节点抛出错误了，对此我特别疑惑，查看了源码，故在此杜撰下我的排查与了解的进展，如有问题，希望您及时指正。

大致执行逻辑：

1. 当我执行 `influxd-ctl copy-shard` 命令时，它会向 http://localhost:8091/copy-shard 发起一个 HTTP 请求，如果本meta节点非领导节点，会进行Http Request转发，最后由主节点执行该命令

2. 主节点执行时，会有两个步骤的 copy-shard 操作，第一步 `CopyShard` 方法和第二步 `copyShard` 方法，下面详细谈下第一步，第二步似乎是维护好meta节点上的分片owner信息，我就不详细展开了

3. 承接上一点，第一步 `CopyShard` 方法，实例化一个 rpcClient 对象

    - 该对象中含有的配置属性，不确定是 influxdb-meta.conf 还是 influxdb.conf 中去取的，是否取的是influxdb.conf 中的 cordinate 项呢
    - 为什么是元节点与目标数据节点dial建立tcp连接呢，我猜是不是为了告诉目标节点分片所在源节点的坐标信息，然后让目标数据节点主动问源数据节点复制分片呢？我增加 dial_timeout 配置项依旧报错超时
    - 那么，为什么这个 i/o timeout 提示的异常是由meta节点抛出呢，意思是meta节点收不到复制结果的响应导致的超时吗？
    - 这是否和 Linux TCP 超时时间配置有关？


最后，我该怎么做才能实现大分片的复制呢

**Comment by JackyeeMe** [comment]
@chengshiwen 
    我补充下，因为持续抛出这个问题，无法正常copy-shard，所以我执行了停机并使用Linux的scp 文件远程传输分片文件夹至目标数据节点，最后重启目标数据节点，居然也可以同步两边数据，真的amazing，所以我真的很想知道influxd-ctl copy-shard 是不是就是做了scp的事儿

**Comment by chengshiwen** [comment]
@JackyeeMe 如果只是误删除，scp是可以解决问题，因为没有改变meta存储的元信息；但是要增加或减少备份，scp就不能改变元信息了

**Comment by chengshiwen** [comment]
1、`h.rpcClient.CopyShard` 是 meta 主节点和对应 data 节点通信，告知对方需要和对应的源 data 节点进行通信拷贝数据。`dial_timeout` 对应的错误是 `dial timout` 相关的错误，而非 `i/o timeout`
2、`i/o timeout` 说明 data 节点通信出了超时问题，`172.25.38.119` 是否是你的一个 data 节点？

**Comment by JackyeeMe** [comment]
> 172.25.38.119:46704->172.25.38.127:8088

是的，是我不小心 删除了 172.25.38.119 节点的一个分片，然后我发起复制，向 172.25.38.127 节点抓取备用分片信息

您说的是data节点超时问题，我就挺疑惑，因为在拷贝我说的50分片前，之前的几个分片都正常拷贝完了， 也没发生这样的超时现象，当我拷贝50时，次次超时，每次大约过了`30s`就超时

**Comment by JackyeeMe** [comment]
@chengshiwen 
   早上好，这次说的和上条又是另外一个超时问题，今天我又细心的发现试用的这一阵子，时不时会发生当我 执行 influx import 命令时出现的 timeout 异常，我跟踪了一下日志，又是出现failed to store statistics" log_id=0o7lAj_l000 service=monitor error=timeout 这种日志，我想它应该与我写入点时出现的超时有关，然后把各个数据节点重启下再导入就又可以导入了，这种奇怪的现象就是有些摸不着头脑

**Comment by JackyeeMe** [comment]
> @chengshiwen 早上好，这次说的和上条又是另外一个超时问题，今天我又细心的发现试用的这一阵子，时不时会发生当我 执行 influx import 命令时出现的 timeout 异常，我跟踪了一下日志，又是出现failed to store statistics" log_id=0o7lAj_l000 service=monitor error=timeout 这种日志，我想它应该与我写入点时出现的超时有关，然后把各个数据节点重启下再导入就又可以导入了，这种奇怪的现象就是有些摸不着头脑

![image](https://github.com/chengshiwen/influxdb-cluster/assets/156211485/c66a1e61-c1e4-4cc2-af9b-be8614d8992f)

**Comment by chengshiwen** [comment]
"failed to store statistics" 这种日志正常，单机偶尔也会经常出现，不影响正常功能

**Comment by JackyeeMe** [comment]
@chengshiwen 
嗨，中午好呀，当发生批量写超时时，然后我尝试仅写入一条数据，就在本数据节点对自己执行写入命令发生了这样的事：
![image](https://github.com/chengshiwen/influxdb-cluster/assets/156211485/e1d14035-439d-45d1-8764-ea698b88c2ed)

**Comment by JackyeeMe** [comment]
> > 172.25.38.119:46704->172.25.38.127:8088
> 
> 是的，是我不小心 删除了 172.25.38.119 节点的一个分片，然后我发起复制，向 172.25.38.127 节点抓取备用分片信息
> 
> 您说的是data节点超时问题，我就挺疑惑，因为在拷贝我说的50分片前，之前的几个分片都正常拷贝完了， 也没发生这样的超时现象，当我拷贝50时，次次超时，每次大约过了`30s`就超时

然后昨日说的这个问题，您能给我些解决思路吗？

**Comment by JackyeeMe** [comment]
> @chengshiwen 嗨，中午好呀，当发生批量写超时时，然后我尝试仅写入一条数据，就在本数据节点对自己执行写入命令发生了这样的事： ![image](https://private-user-images.githubusercontent.com/156211485/316721484-e1d14035-439d-45d1-8764-ea698b88c2ed.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE0Mjc1MjEsIm5iZiI6MTcxMTQyNzIyMSwicGF0aCI6Ii8xNTYyMTE0ODUvMzE2NzIxNDg0LWUxZDE0MDM1LTQzOWQtNDVkMS04NzY0LWVhNjk4Yjg4YzJlZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMyNlQwNDI3MDFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mYjQ1NDJlZGU1NDFjNDRkMzk2M2I0M2E1OWQ5YzQ0OWQxNzEzNGI1MzEyNzBlYWU3NjhjMmI0ZGRkNjdjNjNjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.xeNuIVgw0iDJ4nlAEaxYRvyDZ_-EGQUT8Sub7JgmvRM)

这个问题当我重启这个数据节点时，就能写入了，否则跟服务假死了一样，能查询能连接，就是不能写入，太匪夷所思了。
![image](https://github.com/chengshiwen/influxdb-cluster/assets/156211485/113c720f-23ba-4e9d-b08f-95c5bface896)

**Comment by chengshiwen** [comment]
> 然后昨日说的这个问题，您能给我些解决思路吗？

我看看能不能复现，能麻烦你提供下整个测试或复现的详细步骤吗

**Comment by JackyeeMe** [comment]
> 或复现的详细步骤
@chengshiwen 
Q1：在meta节点调用`copy-shard`命令对data节点超时复制问题
环境：主节点：172.25.38.127备节点
我不小心 删除了 172.25.38.119 节点的一个分片，然后我发起复制，向 172.25.38.127 节点抓取备用分片信息
您说的是data节点超时问题，我就挺疑惑，因为在拷贝我说的50分片前，之前的几个分片都正常拷贝完了， 也没发生这样的超时现象，当我拷贝50时，次次超时，每次大约过了30s就超时

**Comment by JackyeeMe** [comment]
@chengshiwen 
Q3：这个问题我单独说，Amazing，我有四个数据节点 4 5 6 7，复制因子2，两个分片各冗余在 4 7 和 5 6，当查询数据时 5 6 节点返回的field均正常，4 7 节点时不时返回field 为null的情况，而且每次为null的字段还在不断变化，太不可置信了。
分片分布图：
![image](https://github.com/chengshiwen/influxdb-cluster/assets/156211485/dcb0eb66-5931-4a68-b280-9f2b336f1a65)
SQL：
![image](https://github.com/chengshiwen/influxdb-cluster/assets/156211485/029ae5b0-b53b-421a-a091-9d5d59a0ff41)
正常的5 6 节点就不说了，贴下4 7 节点返回数据现象：
![image](https://github.com/chengshiwen/influxdb-cluster/assets/156211485/60cbcf84-a6db-4e18-920e-c9cbe9263a30)
![image](https://github.com/chengshiwen/influxdb-cluster/assets/156211485/4ad922de-4473-4143-8ccb-6510f21454bd)

**Comment by chengshiwen** [comment]
@JackyeeMe Q1 和 Q2，我测试复现下看看，找找原因；Q3 看看是否有可能是数据在不断更新写入，参考 https://github.com/chengshiwen/influxdb-cluster/issues/36 遇到的问题

**Comment by JackyeeMe** [comment]
> @JackyeeMe Q1 和 Q2，我测试复现下看看，找找原因；Q3 看看是否有可能是数据在不断更新写入，参考 #36 遇到的问题


@chengshiwen 
    先在此感谢shiwen对之前问题解答，我这边提个Q4，关于两个冷分片2023-06-25 ~ 2023-07-25这一个月数据散布在两个分片下，如图（看我红框的就行）
![image](https://github.com/chengshiwen/influxdb-cluster/assets/156211485/c1b8c9dd-5a37-4ca4-99b2-8ca9fd29280b)
我的场景是，我在`ID:5 TCPAddr:172.25.38.127:8088`这个节点做2023-06-29 ~ 2023-06-30 查询29这一日的数据时，我发现它抛出了个错误，如图
![image](https://github.com/chengshiwen/influxdb-cluster/assets/156211485/138494e7-eebe-4d27-91ec-3bc638466a28)
抛开这个错误先不谈，恕我才疏学浅，我疑惑的是：同等时间段内的分片，我也是在ID5上执行的SQL查询，为啥它会调用`ID:4 TCPAddr:172.25.38.130:8088`的查询，我想这两个节点对于这个同样的分片，无非就是主备关系呀，ID5上应该也查询得到，为啥它就要去调用ID4的，望您给我解答解答《比心^.^》

**Comment by JackyeeMe** [comment]
> @JackyeeMe Q1 和 Q2，我测试复现下看看，找找原因；Q3 看看是否有可能是数据在不断更新写入，参考 #36 遇到的问题

Q3 我得和你说个前提，我复制因子是2，但我偶然发现我程序里写入用consistency=one，不知是否就是这个问题的元凶？
