### ISSUE TITLE
为什么插入data mate不同步呢数据

### ISSUE THREAD

**Issue by huangchengwu** [chengshiwen/influxdb-cluster#40]
为什么插入data mate不同步呢数据

**Comment by chengshiwen** [comment]
> 为什么插入data mate不同步呢数据

meta 同步数据吗？meta 是保存元数据的，插入数据并不总会涉及到元数据的修改，少数情况下会，比如插入第一条就会生成相应的schema的元数据

**Comment by huangchengwu** [comment]
https://github.com/chengshiwen/influxdb-cluster.git

quorum：当大多数节点（超过一半的复制因子）返回成功时，返回成功。此选项仅在复制因子大于 2 时才有用，否则相当于all。

all：只有所有节点都返回成功才返回成功。



就是使用这两种方式插入数据，然后两个节点只有一个节点有数据呢




~☆随风玉★~
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "chengshiwen/influxdb-cluster"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年6月25日(星期二) 晚上6:40
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [chengshiwen/influxdb-cluster] 为什么插入data mate不同步呢数据 (Issue #40)





  
为什么插入data mate不同步呢数据
  
meta 同步数据吗？meta 是保存元数据的，插入数据并不总会涉及到元数据的修改，少数情况下会，比如插入第一条就会生成相应的schema的元数据

**Comment by chengshiwen** [comment]
如何判定的“两个节点只有一个节点有数据呢”

**Comment by chengshiwen** [comment]
Closed since no updates for long time.
