### ISSUE TITLE
panic: unaligned 64-bit atomic operation

### ISSUE THREAD

**Issue by StephenKathy** [chengshiwen/influxdb-cluster#41]
系统：centOS7.4
内核版本：
![image](https://github.com/user-attachments/assets/b0d5dd7c-feae-4192-a3e4-3b931a17ca73)
influxDB-cluster版本：Release v1.8.10-c1.1.2
![image](https://github.com/user-attachments/assets/98edc7d0-77c0-45c3-8d49-8c55d798c94d)
硬件信息：
![image](https://github.com/user-attachments/assets/10c64931-152c-42e9-a472-3e3fc435e2b8)

1. 建库(单副本)：curl -XPOST "http://influxdb-data-01.sh.td:8086/query" --data-urlencode "q=CREATE DATABASE "test_stress" WITH DURATION 14d REPLICATION 1 SHARD DURATION 5m"
2. 写入数据：curl -XPOST "http://influxdb-data-01.sh.td:8086/write?db=test_stress" \
-d 'cpu,host=server01,region=uswest load=2'
3. 查询数据, client提示: ERR: read message type: EOF, 同时数据所在的data节点 进程宕
![image](https://github.com/user-attachments/assets/fd130e16-b707-4bda-ae5e-40115130d195)
![image](https://github.com/user-attachments/assets/77fe8234-eace-4cb9-a7bb-0565ab4c1c11)

64位操作系统下 建单副本表查询数据 进程会宕机，请问如何解决？

**Comment by chengshiwen** [comment]
你部署的是这个链接里的哪个版本：https://github.com/chengshiwen/influxdb-cluster/releases/tag/v1.8.10-c1.1.2

**Comment by StephenKathy** [comment]
influxdb-cluster_1.8.10-c1.1.2_linux_i386.tar.gz

**Comment by chengshiwen** [comment]
你不能用 i386 这样的 32 位版本，你的系统平台是 linux 64 位，应该用 linux_amd64 或 static_linux_amd64 版本，两个版本主要区别：一是目录结构不同，static 版本扁平组织；二是 static 版本删除了 debug 信息从而包会更小，但无法使用 gdb 等调试分析
