### ISSUE TITLE
【磁盘io配置问题】集群写入性能非常低

### ISSUE THREAD

**Issue by lecssmisc** [chengshiwen/influxdb-cluster#46]
我用了三台32G的服务器，搭建了一个3个MetaNode, 3个DataNode的集群。使用jmh进行压力测试，10个线程同时循环写入，每个线程每次批量写入1000条metric，每次的数据量大约3MB。所有线程1秒钟总共就只能写出不到10次，总的吞吐量低于10000EPS。我看了下服务器，iowait持续高于60%, 磁盘使用率接近100%，但是写入速度却只有几兆一秒。
请问是哪里配置有问题吗？wal刷盘的时间间隔设置的是100ms，其他基本都是默认值。
另外，增加线程数的话，很大可能会出现http  timeout。

**Comment by chengshiwen** [comment]
从反馈只能写出不到10次、每秒只有几兆，有几个可能：
1、每批建议至少5000，一般在10000；
2、主要还是磁盘io的性能问题或者配置不当，`wal-fsync-delay` 只能优化 wal 刷盘
3、iowait高先调整下io相关的参数，降低下io，可以看文档：https://github.com/chengshiwen/influxdb-cluster/wiki/Configure-Key-Settings
4、打开 [coordinator] allow-out-of-order-writes = true，可以提升写入性能
