### ISSUE TITLE
请教一下，加meta节点报错，add-meta: operation exited with error: invalid character '<' looking for beginning of value。

### ISSUE THREAD

**Issue by chenhaoren-1994** [chengshiwen/influxdb-cluster#48]
执行influxd-ctl add-meta bigdata001:8091添加节点时候报错：
add-meta: operation exited with error: invalid character '<' looking for beginning of value。
这是什么原因呢，是因为环境吗还是？
系统：Ubuntu 22.04.4 LTS
go版本：go version go1.23.3 linux/amd64
另，目前支持influxdb的2.X版本不，感谢！

**Comment by chengshiwen** [comment]
跟环境应该没有关系，你执行下 `influxd-ctl show`

**Comment by chengshiwen** [comment]
估计应该是你配置文件里 `hostname` 那个没有去掉 `<` 和 `>`

**Comment by chenhaoren-1994** [comment]
> influxd-ctl show

执行这个是没问题的，
![image](https://github.com/user-attachments/assets/329193b6-d6df-4bc4-a8b4-ec5687f57fa0)
然后这个是配置文件，没找到<，所以很奇怪
![image](https://github.com/user-attachments/assets/3b7d73be-1cec-4cd9-9bd0-6daa01ca64f9)

**Comment by chengshiwen** [comment]
再详细看看 [安装](https://github.com/chengshiwen/influxdb-cluster/wiki#%E5%AE%89%E8%A3%85) 文档，应该就是某个配置没有配置对，检查下配置、停掉实例、重置数据，重新试下

**Comment by chenhaoren-1994** [comment]
> 再详细看看 [安装](https://github.com/chengshiwen/influxdb-cluster/wiki#%E5%AE%89%E8%A3%85) 文档，应该就是某个配置没有配置对，检查下配置、停掉实例、重置数据，重新试下

好的，谢谢，我再看看。另外这版本能支持2.0不

**Comment by chengshiwen** [comment]
不支持2.0
