### ISSUE TITLE
How to install from source code?

### ISSUE THREAD

**Issue by LiuMicheal** [chengshiwen/influxdb-cluster#7]
How to install from source code? Thx!

**Comment by chengshiwen** [comment]
Please refer to [Build and Test](https://github.com/chengshiwen/influxdb-cluster/blob/master/CONTRIBUTING.md#build-and-test), and just use `build.py`:

```
python build.py --help

# Or to run the build utility via Docker
# bash build.sh --help

# Or to build a package for your current system
bash build.sh --package

# Or to build all release packages by specifying the platform, arch, branch and version
bash build.sh --platform all --arch all --branch master --version 1.8.10-c1.0.0 --clean --release --package
```

**Comment by LiuMicheal** [comment]
Ok, I will try it.
Thanks, my bro.




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Shiwen ***@***.***&gt;; 
发送时间: 2022年7月26日(星期二) 下午3:47
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [chengshiwen/influxdb-cluster] How to install from source code? (Issue #7)





 
Please refer to Build and Test, and just use build.py:
 python build.py --help # Or to run the build utility via Docker # bash build.sh --help # Or to build a package for your current system bash build.sh --package # Or to build all release packages by specifying the platform, arch, branch and version bash build.sh --platform all --arch all --branch master --version 1.8.10-c1.0.0 --clean --release --package
