### ISSUE TITLE
meta node can not add data node

### ISSUE THREAD

**Issue by LiuMicheal** [chengshiwen/influxdb-cluster#8]
When I use influxd-ctl add-data influxdb-data-02:8088 in meta-01. I get these: 

root@influxdb-meta-01:~/go/bin# influxd-ctl add-data influxdb-data-02:8088
add-data: operation exited with error: Get "http://localhost:8091/status": dial tcp 127.0.0.1:8091: connect: connection refused

It seems that the meta-01 can not visit data-02 http://localhost:8091.

And here is the output in data-02.
2022-08-01T09:28:30.028071Z	info	Failed to create storage	{"log_id": "0c2B_9Xl000", "service": "monitor", "db_instance": "_internal", "error": "Post \"http://localhost:8091/execute\": dial tcp 127.0.0.1:8091: connect: connection refused"}
2022-08-01T09:28:30.029493Z	info	failed to store statistics	{"log_id": "0c2B_9Xl000", "service": "monitor", "error": "database not found: _internal"}
2022-08-01T09:28:36.979346Z	info	Failure getting snapshot	{"log_id": "0c2B_9Xl000", "service": "metaclient", "server": "localhost:8091", "error": "Get \"http://localhost:8091?index=0\": dial tcp 127.0.0.1:8091: connect: connection refused"}

How can i solve this error? and add data02?

**Comment by chengshiwen** [comment]
Please execute `./influxd-ctl show` and follow [Installation](https://github.com/chengshiwen/influxdb-cluster/wiki#%E5%AE%89%E8%A3%85)

**Comment by chengshiwen** [comment]
It seems that the meta node cluster is not set up properly, and the `hostname` in the configuration file `influxdb-meta.conf` is not set correctly

**Comment by LiuMicheal** [comment]
> It seems that the meta node cluster is not set up properly, and the `hostname` in the configuration file `influxdb-meta.conf` is not set correctly

ok, thx. I will check my influxdb-meta.conf. 
And what need to include in the influxdb-meta.conf? 
I just write one sentence: hostname = "influxdb-meta-01"
maybe I am wrong.

**Comment by chengshiwen** [comment]
@LiuMicheal You can consider entering the WeChat group, it is more convenient to communicate and discuss. please refer to [Community & Communication](https://github.com/chengshiwen/influxdb-cluster/wiki#%E7%A4%BE%E5%8C%BA--%E4%BA%A4%E6%B5%81)

**Comment by LiuMicheal** [comment]
> @LiuMicheal You can consider entering the WeChat group, it is more convenient to communicate and discuss. please refer to [Community & Communication](https://github.com/chengshiwen/influxdb-cluster/wiki#%E7%A4%BE%E5%8C%BA--%E4%BA%A4%E6%B5%81)

ok, i have entered. Thx, my bro.

**Comment by chengshiwen** [comment]
Resolved by WeChat
