### ISSUE TITLE
分布式data node写入性能提高不明显

### ISSUE THREAD

**Issue by BGDSW** [chengshiwen/influxdb-cluster#9]
理论上将data node部署在不同的服务器上可以并发写入，提高写入的效率，但是实践中我发现写入性能并没有提高。
我使用了两台服务器作为两个data node，复制因子设置为1，检查内存发现确实每个服务器上只写入了一半的数据。但是我在向influx-cluster写入380w条数据时用时需要20s（全部请求发送给一个node），我在向一个普通的influxdb写入相同数据时用时也是20s。
请问influx-cluster是不支持多个data node并发写入吗，还是因为我的写入操作问题呢？

**Comment by chengshiwen** [comment]
influxdb cluster因为有meta元数据访问（例如写数据前要检查db是否存在，就需要访问meta节点，有http损耗）和一致性要求（例如写一致性，是多个都要求全部写完还是部分写完，取决于consistency参数），所以分布式的influxdb cluster，性能肯定不会高于单机 influxdb，influxdb cluster主要解决集群（多节点存储一部分数据）、高可用问题，同时提供配套工具influxd-ctl来维护整个集群

**Comment by BGDSW** [comment]
多谢解答！
